stages:
  - test
  - build
  - deploy


#test#
run_unit_test:
  stage: test
  before_script:
    - echo "preparando testes"
  script:
    - echo "run teste"
  after_script:
    - echo "clean"
    
run_lint_tests:
  stage: test
  before_script:
    - echo "preparing test"
  script:  
    - echo "running"
  after_script:
    - echo "clearing test"

#build
build_image:
  stage: build
  script:
    - echo "buil the image"
    - echo "tagg image"

#deploy
push_image:
  stage: deploy
  script:
    - echo "loog docker regs"
    - echo "Push docker image"

